/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/card.vue')['default']
    ComicCard: typeof import('./src/components/comicCard.vue')['default']
    CommentRow: typeof import('./src/components/commentRow.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NIcon: typeof import('naive-ui')['NIcon']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabbar: typeof import('./src/components/tabbar.vue')['default']
    VanCol: typeof import('vant/es')['Col']
    VanIcon: typeof import('vant/es')['Icon']
    VanRow: typeof import('vant/es')['Row']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
  }
}

// For TSX support
declare global {
  const Card: typeof import('./src/components/card.vue')['default']
  const ComicCard: typeof import('./src/components/comicCard.vue')['default']
  const CommentRow: typeof import('./src/components/commentRow.vue')['default']
  const NButton: typeof import('naive-ui')['NButton']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NPopconfirm: typeof import('naive-ui')['NPopconfirm']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Tabbar: typeof import('./src/components/tabbar.vue')['default']
  const VanCol: typeof import('vant/es')['Col']
  const VanIcon: typeof import('vant/es')['Icon']
  const VanRow: typeof import('vant/es')['Row']
  const VanTab: typeof import('vant/es')['Tab']
  const VanTabs: typeof import('vant/es')['Tabs']
  const VanTag: typeof import('vant/es')['Tag']
  const VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
}